import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ReduxProvider } from "@/redux/provider";
import AuthDialog from "@/modules/auth/ui/auth-dialog";
import { TRPCProvider } from "@/trpc/client";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <ReduxProvider>
            <TRPCProvider>
              <AuthDialog />
              {children}
            </TRPCProvider>
          </ReduxProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
